Styles for checkbox
darrynten/vue-data-table pull request #66
Opened 2018-10-16 22:27 UTC by igorsergiichuk

This PR introduces necessary css rules for checkboxes

## Screenshots

## Before
![before](https://user-images.githubusercontent.com/16689051/47051164-c173ba80-d1ab-11e8-95ed-547269e2b3df.png)

## After
![after](https://user-images.githubusercontent.com/16689051/47051170-c8023200-d1ab-11e8-984d-e12702be7f30.png)

2018-10-17 10:11 UTC, darrynten requested changes
I almost prefer the original - perhaps we should make it that it only applies the custom style if an asset is included.

2018-10-17 10:11 UTC, darrynten commented on src/main.js
> +    checkbox: `url(data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20viewBox%3D%220%200%20512%20512%22%3E%3Cpath%20d%3D%22M173.898%20439.404l-166.4-166.4c-9.997-9.997-9.997-26.
Why the encoding? It should match the others.

2018-10-17 10:29 UTC, igorsergiichuk commented on src/main.js
> +    checkbox: `url(data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20viewBox%3D%220%200%20512%20512%22%3E%3Cpath%20d%3D%22M173.898%20439.404l-166.4-166.4c-9.997-9.997-9.997-26.
It only works for me while encoded

2019-09-23 08:43 UTC, darrynten approved these changes

2019-09-23 08:43 UTC, merged